// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ-V4Ktmrr0SHvYQiSZcDXmwX_IoZNf5o',
    appId: '1:997637166600:web:dd4465b3880055af39e3bd',
    messagingSenderId: '997637166600',
    projectId: 'servicioelec-6a592',
    authDomain: 'servicioelec-6a592.firebaseapp.com',
    storageBucket: 'servicioelec-6a592.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcNaNzMWXAv9Nx9-cM6X3rJbAkrV838jA',
    appId: '1:997637166600:android:cd0f99f2372927a139e3bd',
    messagingSenderId: '997637166600',
    projectId: 'servicioelec-6a592',
    storageBucket: 'servicioelec-6a592.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvpqPYnq0g7GbQwqn7-4P7TAzno5KWx5U',
    appId: '1:997637166600:ios:5fbe53e2569380da39e3bd',
    messagingSenderId: '997637166600',
    projectId: 'servicioelec-6a592',
    storageBucket: 'servicioelec-6a592.appspot.com',
    iosClientId: '997637166600-lloeebpf73gqb738k6t3o1pubs8pf782.apps.googleusercontent.com',
    iosBundleId: 'com.eje0701frb.eje0701',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvpqPYnq0g7GbQwqn7-4P7TAzno5KWx5U',
    appId: '1:997637166600:ios:5fbe53e2569380da39e3bd',
    messagingSenderId: '997637166600',
    projectId: 'servicioelec-6a592',
    storageBucket: 'servicioelec-6a592.appspot.com',
    iosClientId: '997637166600-lloeebpf73gqb738k6t3o1pubs8pf782.apps.googleusercontent.com',
    iosBundleId: 'com.eje0701frb.eje0701',
  );
}
